---

- name: purge {{ role_name }} docker images and containers
  docker-compose:
    role: "{{ role_name }}"
    data: "{{ compose_data }}"
    images: "{{ (keep_images is defined and keep_images|bool) | ternary(omit, 'absent') }}"
    containers: absent
